const EMAIL_ACCOUNT_TO_COPY = "ORIGIN_ACCOUNT@gmail.com";
const PASSWORD_ACCOUNT_TO_COPY =
  "PASSWORD";
const EMAIL_ACCOUNT_COPY = "ACCOUNT_COPY@gmail.com";
const PASSWORD_ACCOUNT_COPY = "PASSWORD";

export { EMAIL_ACCOUNT_TO_COPY, PASSWORD_ACCOUNT_TO_COPY, EMAIL_ACCOUNT_COPY, PASSWORD_ACCOUNT_COPY };
